name: stale
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    steps:
      - name: "Close stale issues"
        uses: actions/stale@v9
        with:
          stale-issue-label: stale
          exempt-pr-labels: "pinned,security,enhancement"
          exempt-all-milestones: true
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-stale: 60
          days-before-close: 7
